Added the tests I already had
RLBot/RLBotTraining pull request #5
Opened 2019-01-05 18:17 UTC by jeroen11dijk

Added the tests I already had and put them in the current rotation, let me know what you think of the naming. It is up to date with the master at the time of making this

2019-01-07 15:08 UTC, DomNomNom requested changes

2019-01-07 15:08 UTC, DomNomNom commented on rlbot_configs/single_soccar.cfg
> +participant_config_0 = C:\Users\Jeroen\Documents\RLBotPythonExample-master\NVDerevo\Derevo.cfg
Revert this file and use `alter_config()` instead. 
e.g. https://github.com/RLBot/RLBotTraining/blob/master/run_exercises.py#L50

What I'd like to get to in the near future is so you can have a NVDerevo playlist in this repo but you have some `runner.py` or config which points to your bot but is not checked into RLBotTraining.

2019-01-07 15:41 UTC, DomNomNom commented on rlbot_configs/single_soccar.cfg
> +participant_config_0 = C:\Users\Jeroen\Documents\RLBotPythonExample-master\NVDerevo\Derevo.cfg
I fixed this in commit 6383521.

2019-01-08 13:49 UTC, DomNomNom requested changes

2019-01-08 13:49 UTC, DomNomNom commented on standard_training/exercises/medium_goalie.py
> +
Maybe add some documentation as to how this differs from DefendBallRollingTowardsGoal

2019-01-08 13:49 UTC, DomNomNom commented on run_exercises.py
> +        'Line Save': LineSave(config_path),
This seems to be passing instantly. I'll leave it up to you how to fix it but I don't think we should merge this as is.

2019-01-10 17:23 UTC, jeroen11dijk commented
fixed the things you commented on!

2019-01-10 17:31 UTC, DomNomNom requested changes
This commit message seems totally unrelated and this commit doesn't do much

2019-01-10 17:42 UTC, jeroen11dijk commented
Which commit are you talking about?

2019-01-10 17:56 UTC, DomNomNom commented
I'm talking about commit adb4e36

2019-01-13 15:51 UTC, DomNomNom approved these changes

2019-01-13 15:53 UTC, merged